---
- name: Install php with nessecery extensions
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - php7.0
    - libapache2-mod-php7.0  
    - php7.0-curl 
    - php7.0-json
    - php7.0-gd
    - php7.0-intl
    - php7.0-mcrypt
    - php7.0-xml
    - php7.0-zip
    - php7.0-mbstring 
    - php7.0-soap 
    - php7.0-cli
